### ISSUE TITLE
Add grouping to settings

### ISSUE THREAD

**Issue by xadamxk** [xadamxk/HFX2.0#11]
Sometimes a feature will have multiple setting options.
Implement a way to group multiple settings into it's own group/cell.

**Comment by xadamxk** [comment]
I was working on this but once I started I realized I need to incorporate a way to have multiple settings options before grouping is possible. Can you (@TyrantKingBen ) think of any inputs that could be used for settings other than:

- Checkbox
- Textbox
- Colorpicker (HEX Color)

**Comment by TyrantKingBen** [comment]
A literal button (not a toggle) and a slider might also be useful. I haven't thought a whole lot about how to actually implement it, but I've thought about how to display them. Since were using Bootstrap 4, it wouldn't be too hard to make the settings for each feature expandable (click on the feature and it expands to show auxiliary settings). The default view would be what it is now, just a toggle to enable/disable the feature.

**Comment by TyrantKingBen** [comment]
Something like https://github.com/PrasanthJayaraman/node-widgets is what I had in mind for this. You could define in JSON the extra settings that the feature has and the HTML element would be generated automatically from that. I'm having trouble finding a similar package that is actually maintained. I suppose it's not really that much to implement ourselves which would have to upside of being able to do it with Bootstrap 4 in mind. Could be done with Mustache easily or just regular JS template strings if we want to avoid the extra (non-DEV) dependency. I guess we could also build the popup HTML as part of the gulp build instead of dynamically building it each time the extension is opened.
