### ISSUE TITLE
Implement Force HTTPS on Images

### ISSUE THREAD

**Issue by xadamxk** [xadamxk/HFX2.0#23]
If an image uses HTTP try using HTTPS so it will load.
Only apply to posts and avatars?

**Comment by TyrantKingBen** [comment]
```
$(".post").find("img.mycode_img, .author_avatar img").each((index, img) => {
  if (img.src.startsWith("http://")) {
    img.src = `https://${src.substring(7)}`;
  }
});
```

**Comment by xadamxk** [comment]
> ```
> $(".post").find("img.mycode_img, .author_avatar img").each((index, img) => {
>   if (img.src.startsWith("http://")) {
>     img.src = `https://${img.src.substring(7)}`;
>   }
> });
> ```

Do you know if HF automatically appends http://?
If not, we might a bit of logic for that.

**Comment by TyrantKingBen** [comment]
> > ```
> > $(".post").find("img.mycode_img, .author_avatar img").each((index, img) => {
> >   if (img.src.startsWith("http://")) {
> >     img.src = `https://${img.src.substring(7)}`;
> >   }
> > });
> > ```
> 
> Do you know if HF automatically appends http://?
> If not, we might a bit of logic for that.

It looks like HF forces HTTPS for serving pages. any image that doesn't specify a protocol will default to what the page itself is using. So no protocol image sources aren't an issue. An error event listener could be added before updating the source so that it can be replaced/hidden if the HTTPS load fails.

**Comment by xadamxk** [comment]
Obsolete; implemented on site.
