### ISSUE TITLE
Show Group Status on Groups Page

### ISSUE THREAD

**Issue by xadamxk** [xadamxk/HFX2.0#30]
Show status based on group status. Options include:
- Recruitment Open
- Recruitment Closed
- For Sale

Would require an external file to manage the status's

Inspired by: https://greasyfork.org/en/scripts/15355-groups-recruitment-status

**Comment by xadamxk** [comment]
@TyrantKingBen Do you know of a way we could semi automate this?

I thought it would be a really cool feature but the idea of constantly updating a spreadsheet kind of sucks. But without a backend, I don't know of any other way we could do this unless we made something that allowed people to submit changes that auto generated a PR or something?

Thought you'd have some creative feedback.

**Comment by TyrantKingBen** [comment]
The best thing would be to get some sort of free hosting that has (preferably) a database or some other form of persistent storage. This is also really what the Alerts module should be using (rather than loading a raw gist). I will look into some options tomorrow. I think that hardest part will be finding something that works and has collaboration in mind.

Otherwise, we could add a button that only owners/members of a group can see that will autogenerate an HF private message to us to update something static in the code.

**Comment by xadamxk** [comment]
I would like to stay away from backend solutions at all costs.
I also like the convenience of using a gist.

HFES was a userscript in the past that did the same thing with alerts from their website.
Someone exploited the site and injected ads into everyone's web pages, so security would be a concern with most things.
